# Generated by Django 3.0.2 on 2020-10-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=60, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=60, verbose_name='longitude')),
                ('address', models.CharField(max_length=60, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.ImageField(upload_to='imgpath/', verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('contact_type', models.IntegerField(choices=[(1, 'PHONE'), (2, 'FACEBOOK'), (3, 'EMAIL')], verbose_name='contact_type')),
                ('contact', models.CharField(max_length=200, verbose_name='contact')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestTutorial.Category')),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestTutorial.Branch')),
            ],
        ),
    ]
