# Generated by Django 3.0.2 on 2020-10-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestTutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contact_type',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.IntegerField(choices=[(1, 'PHONE'), (2, 'FACEBOOK'), (3, 'EMAIL')], verbose_name='value')),
                ('value', models.CharField(max_length=255, verbose_name='contact')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_Contact', to='RestTutorial.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestTutorial.Contact'),
        ),
    ]
