# Generated by Django 3.0.2 on 2020-10-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestTutorial', '0003_auto_20201021_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(null=True, upload_to='course_logo', verbose_name='logo'),
        ),
    ]
